# ============================================================
# Browser Configuration

browser.1 = chrome
browser.2 = firefox
browser.3 = safari
headless = false
# ============================================================
# default Configuration

base.Url = https://automationexercise.com/
default wait time in seconds = 10
# ============================================================
# Registration Configuration

registration.time = 5
account.username = mahmoud
account.email = memadbouly@gmail.com
account.password = 510520@Mm
account.day = 16
account.month = 10
account.year = 1993
account.firstname = mahmoud
account.lastname = madboly
account.company = TestCrew
account.address1 = Riyadh, saudi
account.address2 = Ar-raead
account.country = Saudi
account.state = 12345
account.city = Riyadh
account.zipcode = 2222
account.mobile = 0565555555



# ============================================================

